Fixed case where invalid tree submission would cause the memory bus to throw an exception.
Should fix this exception specifically:
```
IndexOutOfRangeException: Index was outside the bounds of the array.
  at GatorDragonGames.JigglePhysics.JiggleMemoryBus.TryAddTransformsToSlice (System.Int32 index, GatorDragonGames.JigglePhysics.JiggleTree jiggleTree) [0x00000] in ./Packages/UnityJigglePhysics-upm/Scripts/JiggleMemoryBus.cs:575
  at GatorDragonGames.JigglePhysics.JiggleMemoryBus.CommitTrees () [0x00000] in ./Packages/UnityJigglePhysics-upm/Scripts/JiggleMemoryBus.cs:775
  at GatorDragonGames.JigglePhysics.JiggleJobs.Simulate (System.Double simulateTime, System.Double realTime) [0x00000] in ./Packages/UnityJigglePhysics-upm/Scripts/JiggleJobs.cs:203
  at GatorDragonGames.JigglePhysics.JigglePhysics.ScheduleSimulate (System.Double fixedCurrentTime, System.Double realTime, System.Single fixedDeltaTime) [0x00000] in ./Packages/UnityJigglePhysics-upm/Scripts/JigglePhysics.cs:50
  at BasisEventDriver.LateUpdate () [0x00000] in ./Packages/com.basis.eventdriver/BasisEventDriver.cs:174
```